name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Prepare artifact
      run: |
        mkdir -p build_artifacts
        cp build/libs/*.jar build_artifacts/

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          cd /path/to/deploy/directory
          ./stop_app.sh || true
          rm -rf *
          exit
        script_after: |
          scp -i ~/.ssh/id_rsa -P ${{ secrets.EC2_PORT }} build_artifacts/*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/path/to/deploy/directory/
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash -s' < ./start_app.sh
